In [1]:
import pandas as pd
identification = pd.read_csv("data/data_identification.csv")
emotion = pd.read_csv("data/emotion.csv")

In [2]:
identification

tweet_id identification
0        0x28cc61           test
1        0x29e452          train
2        0x2b3819          train
3        0x2db41f           test
4        0x2a2acc          train
...           ...            ...
1867530  0x227e25          train
1867531  0x293813          train
1867532  0x1e1a7e          train
1867533  0x2156a5          train
1867534  0x2bb9d2          train

[1867535 rows x 2 columns]

In [3]:
train = identification[identification.identification=="train"]
test = identification[identification.identification=="test"]


In [4]:
emotion

tweet_id       emotion
0        0x3140b1       sadness
1        0x368b73       disgust
2        0x296183  anticipation
3        0x2bd6e1           joy
4        0x2ee1dd  anticipation
...           ...           ...
1455558  0x38dba0           joy
1455559  0x300ea2           joy
1455560  0x360b99          fear
1455561  0x22eecf           joy
1455562  0x2fb282  anticipation

[1455563 rows x 2 columns]

In [5]:
import json
data_list = []
with open("data/tweets_DM.json", "r") as f:
    for line in f:
        data_list.append(json.loads(line)["_source"]["tweet"])

In [6]:
data_list

[{'hashtags': ['Snapchat'],
  'tweet_id': '0x376b20',
  'text': 'People who post "add me on #Snapchat" must be dehydrated. Cuz man.... that\'s <LH>'},
 {'hashtags': ['freepress', 'TrumpLegacy', 'CNN'],
  'tweet_id': '0x2d5350',
  'text': '@brianklaas As we see, Trump is dangerous to #freepress around the world. What a <LH> <LH> #TrumpLegacy.  #CNN'},
 {'hashtags': ['bibleverse'],
  'tweet_id': '0x28b412',
  'text': 'Confident of your obedience, I write to you, knowing that you will do even more than I ask. (Philemon 1:21) 3/4 #bibleverse <LH> <LH>'},
 {'hashtags': [],
  'tweet_id': '0x1cd5b0',
  'text': 'Now ISSA is stalking Tasha 😂😂😂 <LH>'},
 {'hashtags': [],
  'tweet_id': '0x2de201',
  'text': '"Trust is not the same as faith. A friend is someone you trust. Putting faith in anyone is a mistake." ~ Christopher Hitchens <LH> <LH>'},
 {'hashtags': ['authentic', 'LaughOutLoud'],
  'tweet_id': '0x1d755c',
  'text': '@RISKshow @TheKevinAllison Thx for the BEST TIME tonight. What stories! H

In [7]:
tweets = pd.DataFrame(data_list)

In [8]:
tweets

hashtags  tweet_id  \
0                             [Snapchat]  0x376b20   
1          [freepress, TrumpLegacy, CNN]  0x2d5350   
2                           [bibleverse]  0x28b412   
3                                     []  0x1cd5b0   
4                                     []  0x2de201   
...                                  ...       ...   
1867530  [mixedfeeling, butimTHATperson]  0x316b80   
1867531                               []  0x29d0cb   
1867532                               []  0x2a6a4f   
1867533                               []  0x24faed   
1867534                    [Sundayvibes]  0x34be8c   

                                                      text  
0        People who post "add me on #Snapchat" must be ...  
1        @brianklaas As we see, Trump is dangerous to #...  
2        Confident of your obedience, I write to you, k...  
3                      Now ISSA is stalking Tasha 😂😂😂 <LH>  
4        "Trust is not the same as faith. A friend is s...  
...                                                    ...  
1867530  When you buy the last 2 tickets remaining for ...  
1867531  I swear all this hard work gone pay off one da...  
1867532  @Parcel2Go no card left when I wasn't in so I ...  
1867533  Ah, corporate life, where you can date <LH> us...  
1867534             Blessed to be living #Sundayvibes <LH>  

[1867535 rows x 3 columns]

In [9]:
train_data = pd.merge(train, tweets, on = "tweet_id", how="left")
train_data = pd.merge(train_data, emotion, on = "tweet_id")
train_data

tweet_id identification  \
0        0x29e452          train   
1        0x2b3819          train   
2        0x2a2acc          train   
3        0x2a8830          train   
4        0x20b21d          train   
...           ...            ...   
1455558  0x227e25          train   
1455559  0x293813          train   
1455560  0x1e1a7e          train   
1455561  0x2156a5          train   
1455562  0x2bb9d2          train   

                                                  hashtags  \
0                                                       []   
1                                        [spateradio, app]   
2                                                       []   
3        [PUBG, GamersUnite, twitch, BeHealthy, StayPos...   
4                                   [strength, bones, God]   
...                                                    ...   
1455558                                              [rip]   
1455559      [libtards, Hillary, lost, sad, growup, Trump]   
1455560                            [seeds, Joy, GLTChurch]   
1455561                                                 []   
1455562                                                 []   

                                                      text       emotion  
0        Huge Respect🖒 @JohnnyVegasReal talking about l...           joy  
1        Yoooo we hit all our monthly goals with the ne...           joy  
2        @KIDSNTS @PICU_BCH @uhbcomms @BWCHBoss Well do...         trust  
3        Come join @ambushman27 on #PUBG while he striv...           joy  
4        @fanshixieen2014 Blessings!My #strength little...  anticipation  
...                                                    ...           ...  
1455558  @BBCBreaking Such an inspirational talented pe...       disgust  
1455559  And still #libtards won't get off the guy's ba...       sadness  
1455560  When you sow #seeds of service or hospitality ...           joy  
1455561  @lorettalrose Will you be displaying some <LH>...         trust  
1455562                               Lord, I <LH> in you.         trust  

[1455563 rows x 5 columns]

In [10]:
test_data = pd.merge(test, tweets, on = "tweet_id", how = "left")
test_data

tweet_id identification                        hashtags  \
0       0x28cc61           test                              []   
1       0x2db41f           test                              []   
2       0x2466f6           test                  [womendrivers]   
3       0x23f9e9           test                [robbingmembers]   
4       0x1fb4e1           test                              []   
...          ...            ...                             ...   
411967  0x2c4dc2           test                          [kids]   
411968  0x31be7c           test  [inspiringvolunteerawards2017]   
411969  0x1ca58e           test                              []   
411970  0x35c8ba           test                              []   
411971  0x1d941b           test                              []   

                                                     text  
0       @Habbo I've seen two separate colours of the e...  
1       @FoxNews @KellyannePolls No serious self respe...  
2       Looking for a new car, and it says 1 lady owne...  
3       @cineworld “only the brave” just out and fount...  
4       Felt like total dog 💩 going into open gym and ...  
...                                                   ...  
411967  6 year old walks in astounded. Mum! Look how b...  
411968  Only one week to go until the #inspiringvolunt...  
411969  I just got caught up with the manga for "My He...  
411970  Speak only when spoken to and make hot ass mus...  
411971  Know what you want and go for it. Fuck everyon...  

[411972 rows x 4 columns]

In [11]:
import nltk
from sklearn.feature_extraction.text import CountVectorizer
# build analyzers (bag-of-words)
BOW_500 = CountVectorizer(max_features=500, tokenizer=nltk.word_tokenize) 

# apply analyzer to training data
BOW_500.fit(train_data['text'])

C:\Users\Tony\anaconda3\envs\DataMining\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
C:\Users\Tony\anaconda3\envs\DataMining\lib\site-packages\sklearn\feature_extraction\text.py:516: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


CountVectorizer(max_features=500,
                tokenizer=<function word_tokenize at 0x000001B47AF4AB80>)

In [12]:
import keras

# standardize name (X, y) 
X_train = BOW_500.transform(train_data['text'])
y_train = train_data['emotion']

X_test = BOW_500.transform(test_data['text'])


## check dimension is a good habbit 
print('X_train.shape: ', X_train.shape)
print('y_train.shape: ', y_train.shape)
print('X_test.shape: ', X_test.shape)


X_train.shape:  (1455563, 500)
y_train.shape:  (1455563,)
X_test.shape:  (411972, 500)


In [13]:
X_train

<1455563x500 sparse matrix of type '<class 'numpy.int64'>'
	with 18707011 stored elements in Compressed Sparse Row format>

In [78]:
y_train

0                   joy
1                   joy
2                 trust
3                   joy
4          anticipation
               ...     
1455558         disgust
1455559         sadness
1455560             joy
1455561           trust
1455562           trust
Name: emotion, Length: 1455563, dtype: object

In [79]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
label_encoder.fit(y_train)
print('check label: ', label_encoder.classes_)
print('\n## Before convert')
print('y_train[0:4]:\n', y_train[0:4])
print('\ny_train.shape: ', y_train.shape)


def label_encode(le, labels):
    enc = le.transform(labels)
    return keras.utils.to_categorical(enc)

def label_decode(le, one_hot_label):
    dec = np.argmax(one_hot_label, axis=1)
    return le.inverse_transform(dec)

y_train = label_encode(label_encoder, y_train)


print('\n\n## After convert')
print('y_train[0:4]:\n', y_train[0:4])
print('\ny_train.shape: ', y_train.shape)



check label:  ['anger' 'anticipation' 'disgust' 'fear' 'joy' 'sadness' 'surprise'
 'trust']

## Before convert
y_train[0:4]:
 0      joy
1      joy
2    trust
3      joy
Name: emotion, dtype: object

y_train.shape:  (1455563,)


## After convert
y_train[0:4]:
 [[0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0.]]

y_train.shape:  (1455563, 8)


In [80]:
input_shape = X_train.shape[1]
print('input_shape: ', input_shape)

output_shape = len(label_encoder.classes_)
print('output_shape: ', output_shape)

input_shape:  500
output_shape:  8


In [86]:
from keras.models import Model
from keras.layers import Input, Dense
from keras.layers import ReLU, Softmax

# input layer
model_input = Input(shape=(input_shape, ))  # 500
X = model_input

# 1st hidden layer
X_W1 = Dense(units=256)(X)  # 64
H1 = ReLU()(X_W1)

# 2nd hidden layer
H1_W2 = Dense(units=128)(H1)  # 64
H2 = ReLU()(H1_W2)


H2_W3 = Dense(units=64)(H2)  # 64
H3 = ReLU()(H2_W3)
# output layer
H3_W4 = Dense(units=output_shape)(H3)  # 8
H4 = Softmax()(H3_W4)

model_output = H4

# create model
model = Model(inputs=[model_input], outputs=[model_output])

# loss function & optimizer
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# show model construction
model.summary()

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 500)]             0         
                                                                 
 dense_3 (Dense)             (None, 256)               128256    
                                                                 
 re_lu_2 (ReLU)              (None, 256)               0         
                                                                 
 dense_4 (Dense)             (None, 128)               32896     
                                                                 
 re_lu_3 (ReLU)              (None, 128)               0         
                                                                 
 dense_5 (Dense)             (None, 64)                8256      
                                                                 
 re_lu_4 (ReLU)              (None, 64)                0   

In [87]:
from keras.callbacks import CSVLogger



# training setting
epochs = 25
batch_size = 128

# training!
history = model.fit(X_train, y_train, 
                    epochs=epochs, 
                    batch_size=batch_size)
print('training finish')

Epoch 1/25
45487/45487 [==============================] - 160s 3ms/step - loss: 1.3991 - accuracy: 0.4900
Epoch 2/25
45487/45487 [==============================] - 205s 4ms/step - loss: 1.3528 - accuracy: 0.5075
Epoch 3/25
45487/45487 [==============================] - 203s 4ms/step - loss: 1.3350 - accuracy: 0.5138
Epoch 4/25
45487/45487 [==============================] - 227s 5ms/step - loss: 1.3229 - accuracy: 0.5187
Epoch 5/25
45487/45487 [==============================] - 269s 6ms/step - loss: 1.3140 - accuracy: 0.5222
Epoch 6/25
45487/45487 [==============================] - 302s 7ms/step - loss: 1.3071 - accuracy: 0.5250
Epoch 7/25
45487/45487 [==============================] - 296s 6ms/step - loss: 1.3007 - accuracy: 0.5275
Epoch 8/25
45487/45487 [==============================] - 295s 6ms/step - loss: 1.2960 - accuracy: 0.5297
Epoch 9/25
45487/45487 [==============================] - 302s 7ms/step - loss: 1.2919 - accuracy: 0.5314
Epoch 10/25
45487/45487 [=====================

In [88]:
pred_result = model.predict(X_test, batch_size=128)

3219/3219 [==============================] - 11s 3ms/step


In [89]:
pred_result = label_decode(label_encoder, pred_result)

In [90]:
pred_result

array(['disgust', 'sadness', 'joy', ..., 'disgust', 'joy', 'joy'],
      dtype=object)

In [106]:
result = pd.DataFrame(pred_result, columns = ["emotion"])

In [107]:
result

emotion
0            disgust
1            sadness
2                joy
3                joy
4                joy
...              ...
411967         trust
411968  anticipation
411969       disgust
411970           joy
411971           joy

[411972 rows x 1 columns]

In [94]:
tweetID = test_data["tweet_id"]

In [96]:
tweetID

0         0x28cc61
1         0x2db41f
2         0x2466f6
3         0x23f9e9
4         0x1fb4e1
            ...   
411967    0x2c4dc2
411968    0x31be7c
411969    0x1ca58e
411970    0x35c8ba
411971    0x1d941b
Name: tweet_id, Length: 411972, dtype: object

In [108]:
result = pd.concat([tweetID, result], axis=1)

In [109]:
result = result.rename(columns = {"tweet_id" : "id"})

In [111]:
result.to_csv("result.csv", index = False)